name: Build & Push Docker Image

on:
  workflow_dispatch:
    inputs:
      registry:
        description: 'Select which registry to build & push to'
        required: true
        default: 'ALL'
        type: choice
        options:
          - ALL
          - VCR_REGISTRY
          - VCR_HAN_REGISTRY

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set common environment
        run: |
          echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "REGISTRY_INPUT=${{ github.event.inputs.registry }}" >> $GITHUB_ENV

      ###########################
      # VCR_REGISTRY
      ###########################

      - name: Build image for VCR_REGISTRY
        if: env.REGISTRY_INPUT == 'VCR_REGISTRY' || env.REGISTRY_INPUT == 'ALL'
        env:
          REGISTRY: ${{ vars.VCR_REGISTRY }}
          VERSION: ${{ github.ref_name }}
        run: make build-local-images

      - name: Login to VCR_REGISTRY
        if: env.REGISTRY_INPUT == 'VCR_REGISTRY' || env.REGISTRY_INPUT == 'ALL'
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.VCR_REGISTRY }}
          username: ${{ secrets.VCR_USERNAME }}
          password: ${{ secrets.VCR_PASSWORD }}

      - name: Push image to VCR_REGISTRY
        if: env.REGISTRY_INPUT == 'VCR_REGISTRY' || env.REGISTRY_INPUT == 'ALL'
        env:
          REGISTRY: ${{ vars.VCR_REGISTRY }}
          VERSION: ${{ github.ref_name }}
        run: make push-local-images

      ###########################
      # VCR_HAN_REGISTRY
      ###########################

      - name: Build image for VCR_HAN_REGISTRY
        if: env.REGISTRY_INPUT == 'VCR_HAN_REGISTRY' || env.REGISTRY_INPUT == 'ALL'
        env:
          REGISTRY: ${{ vars.VCR_HAN_REGISTRY }}
          VERSION: ${{ github.ref_name }}
        run: make build-local-images

      - name: Login to VCR_HAN_REGISTRY
        if: env.REGISTRY_INPUT == 'VCR_HAN_REGISTRY' || env.REGISTRY_INPUT == 'ALL'
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.VCR_HAN_REGISTRY }}
          username: ${{ secrets.VCR_HAN_USERNAME }}
          password: ${{ secrets.VCR_HAN_PASSWORD }}

      - name: Push image to VCR_HAN_REGISTRY
        if: env.REGISTRY_INPUT == 'VCR_HAN_REGISTRY' || env.REGISTRY_INPUT == 'ALL'
        env:
          REGISTRY: ${{ vars.VCR_HAN_REGISTRY }}
          VERSION: ${{ github.ref_name }}
        run: make push-local-images
