# This is a basic workflow to help you get started with Actions

name: Build and push image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  containerized:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: dev
      # Runs a set of commands using the runners shell
      - name: Containerize the application
        run: |
          TMP_VERSION="v0.0."
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

          # Concatenate the two variables
          export VERSION="${TMP_VERSION}${PR_NUMBER}"
          echo "Version: $VERSION"
          make build-local-images
      - name: Login to vcr.vngcloud.vn
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.VCR_REPOSITORY }}
          username: ${{ secrets.VCR_USERNAME }}
          password: ${{ secrets.VCR_PASSWORD }}
      - name: Push to vcr.vngcloud.vn
        run: |
          TMP_VERSION="v0.0."
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

          # Concatenate the two variables
          export VERSION="${TMP_VERSION}${PR_NUMBER}"
          echo "Version: $VERSION"
          docker image push ${{ secrets.VCR_REPOSITORY }}/vngcloud-blockstorage-csi-driver:$VERSION